name: Manual Update Strapi

on:
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write

jobs:
  update-strapi:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Update Strapi
        run: npm install @strapi/strapi

      - name: Commit changes
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git checkout -B update-strapi
          git add package.json package-lock.json
          git commit -m "chore: update strapi"

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: "chore: update strapi"
          branch: update-strapi
          base: main
          title: "Update Strapi"
          body: "This PR updates Strapi using `npm install @strapi/strapi`."
